# Generated by Django 3.2.3 on 2021-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NormalPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.BigIntegerField()),
                ('cardname', models.CharField(max_length=50)),
                ('cardnumber', models.BigIntegerField()),
                ('expmonth', models.CharField(max_length=50)),
                ('expyear', models.BigIntegerField()),
                ('cvv', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('femail', models.EmailField(max_length=200)),
                ('fphone', models.BigIntegerField()),
                ('fskills', models.CharField(max_length=200)),
                ('fStreet', models.CharField(max_length=200)),
                ('fCity', models.CharField(max_length=200)),
                ('fState', models.CharField(max_length=200)),
                ('fCode', models.BigIntegerField()),
            ],
        ),
    ]
